import slug.std.*;

//
// throwing a catching errors
// --------------------------

var f1 = fn() {
    try {
        println("  before throw")
        throw ConnectionError({msg: "Failed to connect"});
        println("  after throw")
    } catch err {
        {type: "ConnectionError", msg, ...} => println("    Connection failed: " + msg);
        {type: "FileError", ...} => println("    File error");
        // no default case required to re-throw
    }
}

println("before call");

f1();

println("after call");



